### ISSUE TITLE
能否实现SSL双向认证

### ISSUE THREAD

**Issue by DWFLZXJ** [aliyun/gm-jsse#15]
目前只支持单向认证，希望能支持双向认证

**Comment by huarda** [comment]
请问你们解决双向认证问题了吗？

**Comment by huarda** [comment]
> 目前只支持单向认证，希望能支持双向认证

请问你们解决双向认证问题了吗？

**Comment by DWFLZXJ** [comment]
> 

改用GmSSL了

**Comment by huarda** [comment]
> > 
> 
> 改用GmSSL了

你好，有没有相关示例代码，求教
