### ISSUE TITLE
只支持单项GMSSL

### ISSUE THREAD

**Issue by ygy203** [aliyun/gm-jsse#18]
双向什么时候可以支持

**Comment by huarda** [comment]
请问你们解决双向认证问题了吗？

**Comment by ygy203** [comment]
解决此问题了
















在 2023-04-27 15:46:01，"Liu shuhua" ***@***.***> 写道：

请问你们解决双向认证问题了吗？

**Comment by huarda** [comment]
> 解决此问题了 在 2023-04-27 15:46:01，"Liu shuhua" ***@***.***> 写道： 请问你们解决双向认证问题了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

请问怎么解决的，有没有参考代码？

**Comment by JacksonTian** [comment]
v1.3.0 已支持
