### ISSUE TITLE
注释笔误

### ISSUE THREAD

**Issue by xuyang2** [aliyun/gm-jsse#19]
https://github.com/aliyun/gm-jsse/blob/5e2c4bfd945328392c5f71c917884f477b3dfce5/src/main/java/com/aliyun/gmsse/CipherSuite.java#L8-L10

似乎应为：`// ECC-SM2-WITH-SM4-SM3 0x0300E013`

**Comment by gzf1234** [comment]
你是懂参与开源项目的

**Comment by JacksonTian** [comment]
@xuyang2 感谢反馈。确实应该是 0x0300E013
