### ISSUE TITLE
通过commons-httpclient3.1调用会返回空指针的问题，这如何解决？

### ISSUE THREAD

**Issue by zhangyfff** [aliyun/gm-jsse#22]

**Comment by JacksonTian** [comment]
复现代码发一下

**Comment by zhangyfff** [comment]
您好，我已经把调用的部分代码和返回报错，以及问题跟踪情况写在附件里了，您有时间的话可以看看，感谢您提出指导建议。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aliyun/gm-jsse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aliyun/gm-jsse] 通过commons-httpclient3.1调用会返回空指针的问题，这如何解决？ (Issue #22)





 
复现代码发一下

**Comment by JacksonTian** [comment]
发到哪个邮箱了呢

**Comment by zhangyfff** [comment]
发在您主页写的那个邮箱地址了，那个地址还在用嘛？

**Comment by JacksonTian** [comment]
收到了。邮箱发我一下 HttpUtil 这个文件吧。

zhangyfff ***@***.***> 于2023年5月25日周四 10:20写道：

**Comment by JacksonTian** [comment]
试一下最新的1.2.0

**Comment by JacksonTian** [comment]
issue 暂时先关闭了。如果还有问题，请 reopen

**Comment by zhujianhua1230** [comment]
> 发在您主页写的那个邮箱地址了，那个地址还在用嘛？
大佬，能否劳烦把代码发我一下
1228164345@qq.com
